name = "dev-series/exercise"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'dev-series/exercise'"

[repository]
user = "dev-series"
project = "exercise"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.0-beta"
source = "github"

[config]
